In [1]:
#Data.csv

**Step 1: Importing the libraries**

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


**Step 2: Importing dataset**

In [14]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

**Step 3: Handling the missing data**

In [15]:
from sklearn.impute import SimpleImputer
# create a imputer object
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# we should only specify only numerical columns ,so removed 1st column.
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

**Step 4: Encoding categorical data**

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Create a object for column tranformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)

**Step 5: Creating a dummy variable**

In [18]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y = label.fit_transform(y)

**Step 6: Splitting the datasets into training sets and Test sets**

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.3, random_state=42)

**Step 7: Feature Scaling**

In [20]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
 # Use Any scaler object
minmax = MinMaxScaler()
X_train[:, 3:] = minmax.fit_transform(X_train[:, 3:])
X_test[:, 3:] = minmax.transform(X_test[:, 3:])

In [21]:
print(X_train)

[[1.0 0.0 0.0 0.7777777777777777 0.7407407407407407]
 [1.0 0.0 0.0 1.0 1.0000000000000002]
 [0.0 1.0 0.0 0.0 0.07407407407407418]
 [1.0 0.0 0.0 0.38888888888888884 0.5555555555555556]
 [0.0 1.0 0.0 0.5555555555555558 0.43621399176954756]
 [0.0 0.0 1.0 0.44444444444444464 0.33333333333333326]
 [0.0 0.0 1.0 0.48765432098765427 0.0]]


In [22]:
print(X_test)

[[0.0 1.0 0.0 1.1111111111111112 1.1481481481481481]
 [0.0 0.0 1.0 -0.16666666666666652 -0.14814814814814814]
 [1.0 0.0 0.0 0.2777777777777779 0.2222222222222221]]
